cockpit-project/console.dot

nginx.conf
This is what the real infrastructure does, and it will help us to
develop a solution for this aspect.
=> Reject websocket path on /api/

nginx.conf
This is being used to auth the browser against the (3scale/console.dot)
proxy, not against cockpit on the managed server. 3scale drops that
header, do the same here.
=> Don't pass on Authorization: header

webconsoledot-local.yaml
This speeds up development, no need to rebuild the container all the time.
Fixes #8
=> Use multiplexer.py from git

3scale/nginx.conf, appservice/multiplexer.py, webconsoledot-local.yaml
Two pods in the same network don't seem to share the same DNS resolving so switch to one pod. Wire up the new register path and route it to the webconsoleapp.
=> Hook up 3scale to webconsoleapp

3scale/nginx.conf, appservice/multiplexer.py
How I tested it: `make run`, then `podman cp` the systemd and shell into /usr/share/cockpit, then run `websocat -b ws://127.0.0.1:8080 cmd:cockpit-bridge` inside of the container -- then you get a cockpit shell for the container itself.
Fixes #6
~Before we land, let's (1) fix the paths to be what we expect, and the impedance mismatch between 3scale and appservice #10; and then re-test it~ done
=> wire up actual cockpit-ws

appservice/multiplexer.py
Creating a container successfully responds with code 200. Accept any 2XX 
code.
Forward podman's error code on container creation failure, instead of always
replying with 200.
Return the session ID, the caller needs it. 
Fixes #16 
----
Success case:
```
❱❱❱ make run && sleep 2 && curl -v -u admin:foobar -k https://localhost:8443/api/webconsole/v1/sessions/new
< HTTP/1.1 200 OK
{"id": "f73d50b7-a073-4b68-9bd1-e21525abae8c"}
```
Failure case:
```
< HTTP/1.1 404 Not Found
creating container failed: {"cause":"repository name must be lowercase","message":"repository name must be lowercase","response":500}
```
=> appservice: Fix /new response and error handling

3scale/nginx.conf, appservice/multiplexer.py, test/test_basic.py
=> Some small fixes

3scale/nginx.conf
This was an error -- 3scale actually *does* add a `Connection: Upgrade` header on each /wss request. Our multiplexer needs to deal with that somehow.
This reverts commit d694b263cb92175ff876631be75b4b68d1a29fd3.
----
Sorry for the screw-up! Headers with /api:
```
GET /api/webconsole/v1/sessions/f5a65982-5a23-412f-a73b-d8f3da160b61/web/ HTTP/1.1
X-Real-IP: 127.0.0.1
Host: webconsole.cockpit-dev.svc.cluster.local:8080
X-3scale-proxy-secret-token: ...
fakamaienv: test
accept: */*
user-agent: curl/7.85.0
x-forwarded-host: test.cloud.redhat.com
x-forwarded-port: 443
x-forwarded-proto: https
forwarded: for=66.187.232.127;host=api-gateway-dev-3scale-dev.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com;proto=https
x-rh-insights-request-id: 74330a93e26c4787922570693f996bc8
x-rh-identity:
```
vs. on /wss: …
=> Revert "3scale: Don't upgrade all connections"

.flake8, .gitignore, Makefile, README.md, server/Containerfile, server/cockpit-bridge-websocket-connector, test/test_basic.py
We want to minimize the requirements on the target machines. websocat
is a great tool, but not packaged anywhere, and downloading straight
from GitHub isn't appropriate for production.
Thus replace this with a simple Python connector which uses the builtin
asyncio module, and the external websockets one. To avoid having to
install the latter, build a pyz application bundle. We can then also
test/CI this before shipping.
The connector only supports basic auth for now. Eventually it will need
to do TLS client cert auth, but we'll get to that when we have the 
necessary test harness.
Stop putting the connector into the webconsoleserver image. Eventually
it will be sent to the target machine through an Ansible script. Thus
for testing, send it to the container as a volume instead, which from …
=> Replace websocat on target machine with Python script

3scale/nginx.conf, appservice/Containerfile, appservice/multiplexer.py, test/test_basic.py
nginx does not get along well with unavailable proxy_pass targets -- as soon as one session pod unexpectedly goes away (crashes, idle timeouts, networking flakes), it errors out and no session routes can be resolved any more. There are workarounds [1], but I can't get them to work properly. Also, nginx does not allow us to hook into (dis)connection events to implement the session status API (see issue #28).
So it's finally time to grow to something more flexible.
Fixes #36
Fixes #28
[1] https://sandro-keil.de/blog/let-nginx-start-if-upstream-host-is-unavailable-or-down/
------
@tiran FYI
=> appservice: Replace nginx with Starlette reverse proxy, add session status API

Makefile, appservice/Containerfile, appservice/multiplexer.py, appservice/scripts/cockpit-ws-session.sh, appservice/scripts/websocket-session.py
=> Rework session container and startup scripts

Makefile, README.md, appservice/multiplexer.py, appservice/scripts/websocket-session.py, webconsoleapp-k8s-buildconfig.yaml, webconsoleapp-k8s.yaml
Teach appservice to create a k8s pod if it has k8s credentials. Add k8s
resource yaml to deploy the app. For development this uses singular pods
instead of ReplicationControllers.
=> Add deployment to kubernetes

appservice/multiplexer.py, test/test_basic.py
With this, `make check` succeeds for me 4 out of 5 times. Before, it failed 3 out of 4 times. I still get the occasional *loooooong* timeout on `socket.gethostbyname()`, but it's so much better now.
=> appservice: Cache session pod IP addresses

README.md, appservice/closed-session.html, appservice/multiplexer.py, appservice/wait-session.html, test/test_basic.py
Connecting to non-running sessions won't work and just cause a page
hang. Instead, show a stub page which waits for the session to go into
state "running", and then reloads itself to show cockpit.
Fixes #44
Fixes #50
=> appservice: Add session placeholder page

README.md, appservice/multiplexer.py, test/test_basic.py
GET requests should be stateless and our specifcation also notes it should be a POST. In the tests a POST can be requested by specifying the data argument, this works the same as urllib's API. Specifying a data parameter automatically makes the request a POST. This will gives us flexibility for when in the future we need to send some data with a POST request.
Closes #31
=> Make /new a POST

test/test_basic.py
When the session pod dies or the Cockpit session ends, the bridge connector ought to pick up the EOF, close its end, and exit cleanly. Ensure that this happens by validating that the webconsoleserver container exists after crashing the session pod or timing out the cockpit session.
Give the server pods a predictable name for that. This also makes it easier to investigate failures, as session and server pods are now nicely grouped, instead of the latter having auto-generated random names.
Fixes #55
=> test: Ensure that bridge connector picks up EOF

appservice/Containerfile, appservice/multiplexer.py
Our tests did not pick that up because they bind-mount the whole directory into the container. But that does not work on k8s.
Plus some refactoring which I intended to use for fixing #30 in an [initial attempt](https://github.com/cockpit-project/console.dot/commit/6826dc35bc363f633ce7c4a95e2eb04093a11110) -- but that doesn't work, and needs some more thinking. In the meantime, let's fix the container image! If you don't like the refactoring, I'm happy to drop it -- it's not immediately necessary any more.
=> appservice: Add missing HTML files to container; refactor initialization

README.md
Fedora systems typically come with firewalld. Explain how to temporarily open the necessary port with `firewall-cmd` when `cockpit-bridge` is running on a different machine.
=> Mention firewall in README

server/cockpit-bridge-websocket-connector
`cockpit-bridge-websocket-connector` now checks for presence and version of the `cockpit-bridge` program. If the command is missing or too old, the connector script fails with an error message right at the start. Before an outdated Cockpit version resulted in an incomprehensible error on the browser side of the connection.
=> Connector: check cockpit-bridge version

appservice/Containerfile
The shell form does not deliver signals like SIGTERM correctly.
=> Use exec form for CMD

.github/workflows/test.yml
v2 is deprecated.
---
See the warning that we get on workflow runs like https://github.com/cockpit-project/console.dot/actions/runs/3228147201
@marusak , @allisonkarlitskaya : FYI, we need to do this on *all* our projects eventually.
=> workflows: Move to actions/checkout@v3

3scale/nginx.conf, Makefile, README.md, server/cockpit-bridge-websocket-connector, test/test_basic.py
This is a prerequisite for #45, and gets the mechanics and test bits in place. This is incomplete of course -- there is still no "org_id" in the certificate (but `sscg` can add an `--organization=` and other cert fields -- check how a real sub-man cert looks like!), nothing in our code even looks at the X-RH-Identity header, and our fake 3scale does not set the header either. But it already took me some non-trivial time to get these basics.
@jelly over to you for the rest, I figure.
=> Managed machine authentication with TLS client cert
